use_frameworks!

source 'https://github.com/startFromHere/LTPodSpecs.git'

platform :ios, '8.0'

target 'LTSDKDemo_Example' do
  pod 'LTSDKDemo', :path => '../'

  target 'LTSDKDemo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
